//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvotaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        public int id { get; set; }
        public Nullable<int> listId { get; set; }
        public int tipProd { get; set; }
        public Nullable<double> tiraz { get; set; }
        public string ssilk { get; set; }
        public Nullable<double> cebest { get; set; }
        public Nullable<int> kolvoMest { get; set; }
        public Nullable<int> vid1 { get; set; }
        public Nullable<int> param11 { get; set; }
        public Nullable<int> param12 { get; set; }
        public Nullable<double> param13 { get; set; }
        public Nullable<int> vid2 { get; set; }
        public Nullable<int> param21 { get; set; }
        public Nullable<int> param22 { get; set; }
        public Nullable<double> param23 { get; set; }
        public Nullable<int> vid3 { get; set; }
        public Nullable<int> param31 { get; set; }
        public Nullable<int> param32 { get; set; }
        public Nullable<double> param33 { get; set; }
        public Nullable<int> vid4 { get; set; }
        public Nullable<int> param41 { get; set; }
        public Nullable<int> param42 { get; set; }
        public Nullable<double> param43 { get; set; }
        public Nullable<int> pRazm { get; set; }
        public Nullable<int> pCvet { get; set; }
        public Nullable<int> pPlotn { get; set; }
        public Nullable<int> pLamin { get; set; }
        public Nullable<int> pBigov { get; set; }
        public Nullable<int> pDirk { get; set; }
        public Nullable<int> bVid { get; set; }
        public Nullable<int> bMat { get; set; }
        public Nullable<int> bPost1 { get; set; }
        public Nullable<int> bPost2 { get; set; }
        public Nullable<int> bPost3 { get; set; }
        public Nullable<int> bPost4 { get; set; }
        public Nullable<int> bPost5 { get; set; }
        public Nullable<int> bPost6 { get; set; }
        public Nullable<int> bPost7 { get; set; }
        public Nullable<int> bPost8 { get; set; }
        public Nullable<int> bPost9 { get; set; }
        public Nullable<double> total { get; set; }
        public string totalLabel { get; set; }
        public Nullable<int> bDpi { get; set; }
        public bool param55 { get; set; }
        public bool param14 { get; set; }
        public bool param24 { get; set; }
        public bool param34 { get; set; }
        public bool param44 { get; set; }
        public bool param15 { get; set; }
        public bool param25 { get; set; }
        public bool param35 { get; set; }
        public bool param45 { get; set; }
        public Nullable<int> subTipProd { get; set; }
    }
}
