//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvotaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int id { get; set; }
        public int catId { get; set; }
        public string subtip { get; set; }
        public int tiraz { get; set; }
        public double cena { get; set; }
        public Nullable<double> firma0 { get; set; }
        public Nullable<int> firma { get; set; }
        public bool isAllTiraz { get; set; }
    }
}
