//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvotaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabotnik
    {
        public int id { get; set; }
        public string login { get; set; }
        public string passw { get; set; }
        public int uroven { get; set; }
    }
}
